### ISSUE TITLE
'java.util.concurrent.ThreadPoolExecutor' that could not be found

### ISSUE THREAD

**Issue by JinChee** [Weasley-J/multiple-sms-spring-boot#1]
### **Parameter 1 of constructor in cn.alphahub.multiple.sms.SmsTemplate required a bean of type 'java.util.concurrent.ThreadPoolExecutor' that could not be found.**

![NZ9` SX1VQVU}VG@R_8K9@V](https://user-images.githubusercontent.com/7993699/226090439-0cfcb9dd-fb7d-4779-bd61-7f458d65417b.png)
![4N C)_E(HS256%URZQ{VEPN](https://user-images.githubusercontent.com/7993699/226090446-369f06bd-eab0-4b77-98e4-d23cb9d9f8f1.png)

**Comment by julxxy** [comment]
> ### **Parameter 1 of constructor in cn.alphahub.multiple.sms.SmsTemplate required a bean of type 'java.util.concurrent.ThreadPoolExecutor' that could not be found.**
> ![NZ9` SX1VQVU}VG@R_8K9@V](https://user-images.githubusercontent.com/7993699/226090439-0cfcb9dd-fb7d-4779-bd61-7f458d65417b.png) ![4N C)_E(HS256%URZQ{VEPN](https://user-images.githubusercontent.com/7993699/226090446-369f06bd-eab0-4b77-98e4-d23cb9d9f8f1.png)

感谢反馈，v1.0.9中已经修复，Maven中央仓库同步会稍晚点

**Comment by JinChee** [comment]
ok
